In [1]:
# NUMPY ARRAYS

In [2]:
import numpy as np
a = np.array([1,2,3,4])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(5,dtype="int64")

array([0, 0, 0, 0, 0], dtype=int64)

In [5]:
np.ones(5,dtype="int32")

array([1, 1, 1, 1, 1])

In [15]:
np.empty(2)

array([1., 2.])

In [17]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.linspace(0,10 , num =5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.sort([1,4,2,3,6,5])

array([1, 2, 3, 4, 5, 6])

In [21]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])