In [2]:
# NUMPY ARRAYS

In [3]:
import numpy as np
a = np.array([1,2,3,4])

In [7]:
np.empty(2)

array([ 3.69964218e-236, -3.87960536e+129])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.linspace(0,10 , num =5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.sort([1,4,2,3,6,5])

array([1, 2, 3, 4, 5, 6])

In [11]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
# Creating 2D array
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
# Creating 3D array
c = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

Initial PlaceHolder in Numpy Array

In [ ]:
np.zeros(5,dtype="int64")

array([0, 0, 0, 0, 0], dtype=int64)

In [16]:
np.ones((5,4),dtype="int32")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.zeros((5,2),dtype=int)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])